/obj/structure/retail/black_market
	products_list = list(
		new /datum/data/retail_product("lighter",		/obj/item/lighter/greyscale,	10),
		new /datum/data/retail_product("zippo lighter",	/obj/item/lighter,	20),
		new /datum/data/retail_product("Bailer", /obj/item/bailer, 20),
		new /datum/data/retail_product("Weed Seed", /obj/item/weedseed, 20),
		new /datum/data/retail_product("cannabis puff",		/obj/item/clothing/mask/cigarette/rollie/cannabis,	40),
		new /datum/data/retail_product("bong",	/obj/item/bong,		50),
		new /datum/data/retail_product("lockpick",	/obj/item/vamp/keys/hack, 50),
		new /datum/data/retail_product("LSD pill bottle",		/obj/item/storage/pill_bottle/lsd,	50),
		new /datum/data/retail_product("knife",	/obj/item/melee/vampirearms/knife,	85),
		new /datum/data/retail_product("switchblade",	/obj/item/melee/vampirearms/knife/switchblade, 85),
		new /datum/data/retail_product("stake",	/obj/item/vampire_stake,	100),
		new /datum/data/retail_product("Surgery dufflebag", /obj/item/storage/backpack/duffelbag/med/surgery, 100),
		new /datum/data/retail_product("snub-nose revolver",	/obj/item/gun/ballistic/vampire/revolver/snub,	100),
		new /datum/data/retail_product("cannabis package",		/obj/item/weedpack,	700),
		new /datum/data/retail_product("morphine syringe",	/obj/item/reagent_containers/syringe/contraband/morphine,	800),
		new	/datum/data/retail_product("meth package",	/obj/item/reagent_containers/food/drinks/meth,	800),
		new	/datum/data/retail_product("cocaine package",	/obj/item/reagent_containers/food/drinks/meth/cocaine,	800),
		new /datum/data/retail_product("silver 9mm ammo",	/obj/item/ammo_box/vampire/c9mm/silver,	5000),
		new /datum/data/retail_product("silver .45 ACP ammo",	/obj/item/ammo_box/vampire/c45acp/silver,	6000),
		new /datum/data/retail_product("silver .44 ammo",	/obj/item/ammo_box/vampire/c44/silver,	7000),
		new /datum/data/retail_product("silver 5.56 ammo",	/obj/item/ammo_box/vampire/c556/silver,	8000),
		new /datum/data/retail_product("incendiary 5.56 ammo",	/obj/item/ammo_box/vampire/c556/incendiary,	9000)
	)