/obj/structure/retail/clothing_store
	desc = "Purchase all the finest outfits.. Or don't wagie.."
	products_list = list(new /datum/data/retail_product("crimson red dress",	/obj/item/clothing/under/vampire/primogen_toreador/female	,	350),
		new /datum/data/retail_product("black dress",	/obj/item/clothing/under/vampire/business,	250),
		new /datum/data/retail_product("leather pants", /obj/item/clothing/under/vampire/leatherpants,	200),
		new /datum/data/retail_product("fancy gray suit",	/obj/item/clothing/under/vampire/fancy_gray,	150),
		new /datum/data/retail_product("fancy red suit",	/obj/item/clothing/under/vampire/fancy_red,	150),
		new /datum/data/retail_product("black luxury suit",	/obj/item/clothing/under/vampire/ventrue,	50),
		new /datum/data/retail_product("black luxury suit skirt",	/obj/item/clothing/under/vampire/ventrue/female,	50),
		new /datum/data/retail_product("white buisness suit",	/obj/item/clothing/under/vampire/office,	50),
		new /datum/data/retail_product("black overcoat",	/obj/item/clothing/under/vampire/rich,	45),
		new /datum/data/retail_product("burgundy suit",	/obj/item/clothing/under/vampire/tremere,	35),
		new /datum/data/retail_product("burgundy suit skirt",	/obj/item/clothing/under/vampire/tremere/female,	35),
		new /datum/data/retail_product("plain black suit",	 /obj/item/clothing/under/vampire/suit,	50),
		new /datum/data/retail_product("plain black suitskirt",	 /obj/item/clothing/under/vampire/suit/female,	50),
		new /datum/data/retail_product("plain red suit",	 /obj/item/clothing/under/vampire/sheriff,	80),
		new /datum/data/retail_product("plain red suitskirt",	 /obj/item/clothing/under/vampire/sheriff/female,	80),
		new /datum/data/retail_product("plain blue suit",	 /obj/item/clothing/under/vampire/clerk,	90),
		new /datum/data/retail_product("plain blue suitskirt",	 /obj/item/clothing/under/vampire/clerk/female,	90),
		new /datum/data/retail_product("brown suit",	 /obj/item/clothing/under/vampire/archivist,	60),
		new /datum/data/retail_product("brown suitskirt",	 /obj/item/clothing/under/vampire/archivist/female,	60),
		new /datum/data/retail_product("grey suit slacks", /obj/item/clothing/under/vampire/vtr/suit, 40),
		new /datum/data/retail_product("white shirt and waistcoat", /obj/item/clothing/under/vampire/vtr/suit/waistcoat, 60),
		new /datum/data/retail_product("tan dress shirt", /obj/item/clothing/under/vampire/vtr/suit/tanshirt, 40),
		new /datum/data/retail_product("tan shirt and waistcoat", /obj/item/clothing/under/vampire/vtr/suit/tanshirtwaistcoat, 60),
		new /datum/data/retail_product("grey suit skirt", /obj/item/clothing/under/vampire/vtr/suit/greyskirt, 40),
		new /datum/data/retail_product("black suit slacks", /obj/item/clothing/under/vampire/vtr/suit/black, 50),
		new /datum/data/retail_product("black suit skirt", /obj/item/clothing/under/vampire/vtr/suit/blackskirt, 50),
		new /datum/data/retail_product("blue suit slacks", /obj/item/clothing/under/vampire/vtr/suit/blue, 50),
		new /datum/data/retail_product("blue suit skirt", /obj/item/clothing/under/vampire/vtr/suit/blueskirt, 50),
		new /datum/data/retail_product("purple suit slacks", /obj/item/clothing/under/vampire/vtr/suit/purple, 50),
		new /datum/data/retail_product("purple suit skirt", /obj/item/clothing/under/vampire/vtr/suit/purpleskirt, 50),
		new /datum/data/retail_product("charcoal suit slacks", /obj/item/clothing/under/vampire/vtr/suit/charcoal, 50),
		new /datum/data/retail_product("charcoal suit skirt", /obj/item/clothing/under/vampire/vtr/suit/charcoalskirt, 50),
		new /datum/data/retail_product("navy suit slacks", /obj/item/clothing/under/vampire/vtr/suit/navy, 50),
		new /datum/data/retail_product("navy suit skirt", /obj/item/clothing/under/vampire/vtr/suit/navyskirt, 50),
		new /datum/data/retail_product("burgundy suit slacks", /obj/item/clothing/under/vampire/vtr/suit/burgundy, 50),
		new /datum/data/retail_product("burgundy suit skirt", /obj/item/clothing/under/vampire/vtr/suit/burgundyskirt, 50),
		new /datum/data/retail_product("checkered suit slacks", /obj/item/clothing/under/vampire/vtr/suit/checkered, 50),
		new /datum/data/retail_product("checkered suit skirt", /obj/item/clothing/under/vampire/vtr/suit/checkeredskirt, 50),
		new /datum/data/retail_product("tan suit slacks", /obj/item/clothing/under/vampire/vtr/suit/tan, 50),
		new /datum/data/retail_product("tan suit skirt", /obj/item/clothing/under/vampire/vtr/suit/tanskirt, 50),
		new /datum/data/retail_product("black pantsuit", /obj/item/clothing/under/vampire/vtr/suit/blackfem, 50),
		new /datum/data/retail_product("plain suspenders outfit", /obj/item/clothing/under/vampire/vtr/suspenders, 50),
		new /datum/data/retail_product("fancy suspenders outfit", /obj/item/clothing/under/vampire/vtr/suspenders_fancy, 150),
		new /datum/data/retail_product("flamboyant outfit",	/obj/item/clothing/under/vampire/toreador,	30),
		new /datum/data/retail_product("female flamboyant outfit",	/obj/item/clothing/under/vampire/toreador/female,	30),
		new /datum/data/retail_product("purple and black outfit",	/obj/item/clothing/under/vampire/sexy,	25),
		new /datum/data/retail_product("high-waisted trousers", /obj/item/clothing/under/vampire/vtr/hightrousers, 60),
		new /datum/data/retail_product("high-waisted skirt", /obj/item/clothing/under/vampire/vtr/highskirt, 60),
		new /datum/data/retail_product("black corset", /obj/item/clothing/under/vampire/vtr/dress/black_corset, 40),
		new /datum/data/retail_product("dark red dress", /obj/item/clothing/under/vampire/vtr/dress/darkred, 60),
		new /datum/data/retail_product("little black dress", /obj/item/clothing/under/vampire/vtr/dress/littleblackdress, 60),
		new /datum/data/retail_product("yellow swoop dress", /obj/item/clothing/under/vampire/vtr/dress/yellowswoop, 60),
		new /datum/data/retail_product("black tango dress", /obj/item/clothing/under/vampire/vtr/dress/blacktango, 60),
		new /datum/data/retail_product("qipao", /obj/item/clothing/under/vampire/vtr/dress/qipao2, 60),
		new /datum/data/retail_product("striped dress", /obj/item/clothing/under/vampire/vtr/dress/stripeddress, 40),
		new /datum/data/retail_product("sailor dress", /obj/item/clothing/under/vampire/vtr/dress/sailordress, 40),
		new /datum/data/retail_product("black skirt", /obj/item/clothing/under/vampire/vtr/skirt/outfit, 30),
		new /datum/data/retail_product("blue plaid skirt", /obj/item/clothing/under/vampire/vtr/skirt/outfit/plaid_blue, 30),
		new /datum/data/retail_product("purple plaid skirt", /obj/item/clothing/under/vampire/vtr/skirt/outfit/plaid_purple, 30),
		new /datum/data/retail_product("red plaid skirt", /obj/item/clothing/under/vampire/vtr/skirt/outfit/plaid_red, 30),
		new /datum/data/retail_product("slick jacket",	/obj/item/clothing/under/vampire/slickback,		25),
		new /datum/data/retail_product("tracksuit",	/obj/item/clothing/under/vampire/sport,	25),
		new /datum/data/retail_product("messy shirt",	/obj/item/clothing/under/vampire/bouncer,	15),
		new /datum/data/retail_product("blue overals",	/obj/item/clothing/under/vampire/mechanic,	20),
		new /datum/data/retail_product("rugged attire",	/obj/item/clothing/under/vampire/gangrel,	15),
		new /datum/data/retail_product("female rugged attire",	/obj/item/clothing/under/vampire/gangrel/female,	15),
		new /datum/data/retail_product("yellow sleeveless shirt",	/obj/item/clothing/under/vampire/larry,	15),
		new /datum/data/retail_product("white sleeveless shirt",	/obj/item/clothing/under/vampire/bandit,	15),
		new /datum/data/retail_product("white turtleneck", /obj/item/clothing/under/vampire/turtleneck_white,	15),
		new /datum/data/retail_product("black turtleneck", /obj/item/clothing/under/vampire/turtleneck_black,	15),
		new /datum/data/retail_product("red turtleneck",	/obj/item/clothing/under/vampire/turtleneck_red,	15),
		new /datum/data/retail_product("navy turtleneck",	/obj/item/clothing/under/vampire/turtleneck_navy,	15),
		new /datum/data/retail_product("biker outfit",	/obj/item/clothing/under/vampire/biker,	15),
		new /datum/data/retail_product("daisy dukes", /obj/item/clothing/under/vampire/burlesque/daisyd,	10),
		new /datum/data/retail_product("black shoes",	/obj/item/clothing/shoes/vampire,	10),
		new /datum/data/retail_product("brown shoes",	/obj/item/clothing/shoes/vampire/brown,	10),
		new /datum/data/retail_product("white shoes",	/obj/item/clothing/shoes/vampire/white,	10),
		new /datum/data/retail_product("black boots",	/obj/item/clothing/shoes/vampire/jackboots,	10),
		new /datum/data/retail_product("work boots",	/obj/item/clothing/shoes/vampire/jackboots/work,	10),
		new /datum/data/retail_product("sneakers",	/obj/item/clothing/shoes/vampire/sneakers,	10),
		new /datum/data/retail_product("red sneakers",	/obj/item/clothing/shoes/vampire/sneakers/red,	10),
		new /datum/data/retail_product("blue sneakers",	/obj/item/clothing/shoes/vampire/vtr/sneakers_blue,	10),
		new /datum/data/retail_product("high heels",	/obj/item/clothing/shoes/vampire/heels,	35),
		new /datum/data/retail_product("red high heels",	/obj/item/clothing/shoes/vampire/heels/red,	35),
		new /datum/data/retail_product("black flats", 	/obj/item/clothing/shoes/vampire/vtr/flats, 35),
		new /datum/data/retail_product("brown flats", 	/obj/item/clothing/shoes/vampire/vtr/flats/brown, 35),
		new /datum/data/retail_product("white flats", 	/obj/item/clothing/shoes/vampire/vtr/flats/white, 35),
		new /datum/data/retail_product("red flats", 	/obj/item/clothing/shoes/vampire/vtr/flats/red, 35),
		new /datum/data/retail_product("orange flats", 	/obj/item/clothing/shoes/vampire/vtr/flats/orange, 35),
		new /datum/data/retail_product("purple flats", 	/obj/item/clothing/shoes/vampire/vtr/flats/purple, 35),
		new /datum/data/retail_product("blue flats", 	/obj/item/clothing/shoes/vampire/vtr/flats/blue, 35),
		new /datum/data/retail_product("scaly shoes",	/obj/item/clothing/shoes/vampire/businessscaly,	35),
		new /datum/data/retail_product("black shoes",	/obj/item/clothing/shoes/vampire/businessblack,	35),
		new /datum/data/retail_product("metal tip shoes",	/obj/item/clothing/shoes/vampire/businesstip,	50),
		new /datum/data/retail_product("purple fur coat",		/obj/item/clothing/suit/vampire/slickbackcoat,	500),
		new /datum/data/retail_product("too much fancy jacket",	/obj/item/clothing/suit/vampire/majima_jacket,	100),
		new /datum/data/retail_product("labcoat",	/obj/item/clothing/suit/vampire/labcoat,	75),
		new /datum/data/retail_product("fancy gray jacket",	/obj/item/clothing/suit/vampire/fancy_gray,	50),
		new /datum/data/retail_product("fancy red jacket",	/obj/item/clothing/suit/vampire/fancy_red,	50),
		new /datum/data/retail_product("blue suit jacket", /obj/item/clothing/suit/toggle/vtr/suitjacket/blue, 50),
		new /datum/data/retail_product("purple suit jacket", /obj/item/clothing/suit/toggle/vtr/suitjacket/purple, 50),
		new /datum/data/retail_product("black suit jacket", /obj/item/clothing/suit/toggle/vtr/suitjacket/black, 50),
		new /datum/data/retail_product("charcoal suit jacket", /obj/item/clothing/suit/vampire/vtr/charcoalsuit, 50),
		new /datum/data/retail_product("navy suit jacket", /obj/item/clothing/suit/vampire/vtr/navysuit, 50),
		new /datum/data/retail_product("burgundy suit jacket", /obj/item/clothing/suit/vampire/vtr/burgundysuit, 50),
		new /datum/data/retail_product("checkered suit jacket", /obj/item/clothing/suit/vampire/vtr/checkeredsuit, 50),
		new /datum/data/retail_product("tan suit jacket", /obj/item/clothing/suit/vampire/vtr/tansuit, 50),
		new /datum/data/retail_product("greatcoat", /obj/item/clothing/suit/vampire/vtr/greatcoat, 40),
		new /datum/data/retail_product("black trenchcoat",	/obj/item/clothing/suit/vampire/trench,	45),
		new /datum/data/retail_product("brown trenchcoat",	/obj/item/clothing/suit/vampire/trench/alt,	35),
		new /datum/data/retail_product("classic trenchcoat", /obj/item/clothing/suit/vampire/vtr/det_trench, 45),
		new /datum/data/retail_product("grey trenchcoat", /obj/item/clothing/suit/vampire/vtr/det_trench_grey, 45),
		new /datum/data/retail_product("brown coat",	/obj/item/clothing/suit/vampire/coat,	15),
		new /datum/data/retail_product("green coat",	/obj/item/clothing/suit/vampire/coat/alt,	15),
		new /datum/data/retail_product("black coat",	/obj/item/clothing/suit/vampire/coat/winter,	15),
		new /datum/data/retail_product("red coat",	/obj/item/clothing/suit/vampire/coat/winter/alt,	15),
		new /datum/data/retail_product("letterman jacket", /obj/item/clothing/suit/jacket/letterman, 30),
		new /datum/data/retail_product("letterman jacket, red", /obj/item/clothing/suit/jacket/letterman_red, 30),
		new /datum/data/retail_product("letterman jacket, UCLA", /obj/item/clothing/suit/vampire/vtr/letterman_c, 30),
		new /datum/data/retail_product("yellow aviators",	/obj/item/clothing/glasses/vampire/yellow,	20),
		new /datum/data/retail_product("red aviators",	/obj/item/clothing/glasses/vampire/red,	20),
		new /datum/data/retail_product("sunglasses",	/obj/item/clothing/glasses/vampire/sun,	20),
		new /datum/data/retail_product("prescription glasses",	/obj/item/clothing/glasses/vampire/perception,	20),
		new /datum/data/retail_product("leather gloves", /obj/item/clothing/gloves/vampire/leather,	25),
		new /datum/data/retail_product("rubber gloves", /obj/item/clothing/gloves/vampire/cleaning,	15),
		new /datum/data/retail_product("latex gloves", /obj/item/clothing/gloves/vampire/latex,	5),
		new /datum/data/retail_product("black work gloves", /obj/item/clothing/gloves/vampire/work,	45),
		new /datum/data/retail_product("bandana",	/obj/item/clothing/head/vampire/bandana,	10),
		new /datum/data/retail_product("red bandana",	/obj/item/clothing/head/vampire/bandana/red,	10),
		new /datum/data/retail_product("black bandana",	/obj/item/clothing/head/vampire/bandana/black,	10),
		new /datum/data/retail_product("baseball cap", /obj/item/clothing/head/vampire/baseballcap, 10),
		new /datum/data/retail_product("ushanka",	/obj/item/clothing/head/vampire/ushanka, 20),
		new /datum/data/retail_product("beanie",	/obj/item/clothing/head/vampire/beanie,	10),
		new /datum/data/retail_product("black beanie",	/obj/item/clothing/head/vampire/beanie/black,	10),
		new /datum/data/retail_product("rough beanie",	/obj/item/clothing/head/vampire/beanie/homeless,	10),
		new /datum/data/retail_product("scarf",	/obj/item/clothing/neck/vampire/scarf,	10),
		new /datum/data/retail_product("red scarf",	/obj/item/clothing/neck/vampire/scarf/red,	10),
		new /datum/data/retail_product("blue scarf",	/obj/item/clothing/neck/vampire/scarf/blue,	10),
		new /datum/data/retail_product("green scarf",	/obj/item/clothing/neck/vampire/scarf/green,	10),
		new /datum/data/retail_product("white scarf",	/obj/item/clothing/neck/vampire/scarf/white,	10),
		new /datum/data/retail_product("black tie", /obj/item/clothing/neck/vtr/tie, 30),
		new /datum/data/retail_product("blue tie", /obj/item/clothing/neck/vtr/tie/blue, 30),
		new /datum/data/retail_product("blue tie with clip", /obj/item/clothing/neck/vtr/tie/blueclip, 35),
		new /datum/data/retail_product("long blue tie", /obj/item/clothing/neck/vtr/tie/bluelong, 30),
		new /datum/data/retail_product("red tie", /obj/item/clothing/neck/vtr/tie/red, 30),
		new /datum/data/retail_product("red tie with clip", /obj/item/clothing/neck/vtr/tie/redclip, 35),
		new /datum/data/retail_product("long red tie", /obj/item/clothing/neck/vtr/tie/redlong, 30),
		new /datum/data/retail_product("navy tie", /obj/item/clothing/neck/vtr/tie/navy, 30),
		new /datum/data/retail_product("yellow tie", /obj/item/clothing/neck/vtr/tie/yellow, 30),
		new /datum/data/retail_product("white tie", /obj/item/clothing/neck/vtr/tie/white, 30),
		new /datum/data/retail_product("dark green tie", /obj/item/clothing/neck/vtr/tie/darkgreen, 30),
		new /datum/data/retail_product("horrible tie", /obj/item/clothing/neck/vtr/tie/horrible, 10),
		new /datum/data/retail_product("duffelbag",	/obj/item/storage/backpack/duffelbag,	100),
		new /datum/data/retail_product("satchel",		/obj/item/storage/backpack/satchel,		100),
		new /datum/data/retail_product("leather satchel",		/obj/item/storage/backpack/satchel/leather,		150),
		new /datum/data/retail_product("royal red suit",	/obj/item/clothing/under/vampire/vtr/royalredsuit,	75),
		new /datum/data/retail_product("sheer lace black dress",	/obj/item/clothing/under/vampire/vtr/dress/laceblack,	100),
		new /datum/data/retail_product("loose open-front silk shirt",	/obj/item/clothing/under/vampire/vtr/novella,	50)
	)
