/obj/structure/retail/hot_ishu
	products_list = list(
		new /datum/data/retail_product("\"Vase\"",	/obj/item/bong,		50),
		new /datum/data/retail_product("cross",	/obj/item/card/id/hunter,  25),
		new /datum/data/retail_product("electric guitar", /obj/item/melee/vampirearms/eguitar, 400),
		new /datum/data/retail_product("backpack",	/obj/item/storage/backpack,	100),
		new /datum/data/retail_product("black fur boots", /obj/item/clothing/shoes/vampire/vtr/blackfur, 20),
		new /datum/data/retail_product("black grunge outfit",	/obj/item/clothing/under/vampire/black,	20),
		new /datum/data/retail_product("brown fur boots", /obj/item/clothing/shoes/vampire/vtr/brownfur, 20),
		new /datum/data/retail_product("burlesque outfit", /obj/item/clothing/under/vampire/burlesque,	15),
		new /datum/data/retail_product("female gimp outfit",	/obj/item/clothing/under/vampire/nosferatu/female,	15),
		new /datum/data/retail_product("female punk attire ",	/obj/item/clothing/under/vampire/brujah/female,	20),
		new /datum/data/retail_product("gimp outfit",	/obj/item/clothing/under/vampire/nosferatu,	15),
		new /datum/data/retail_product("gothic clothes",	/obj/item/clothing/under/vampire/gothic,	20),
		new /datum/data/retail_product("gothic attire",	/obj/item/clothing/under/vampire/brujah,	20),
		new /datum/data/retail_product("grimey pants",	/obj/item/clothing/under/vampire/malkavian,	20),
		new /datum/data/retail_product("black frilly dress", /obj/item/clothing/under/vampire/vtr/dress/blackfrilly, 40),
		new /datum/data/retail_product("frilly headband", /obj/item/clothing/head/vampire/vtr/frillyheadband, 10),
		new /datum/data/retail_product("hoodie", /obj/item/clothing/suit/hooded/hoodie, 15),
		new /datum/data/retail_product("intruder pim hoodie", /obj/item/clothing/suit/hooded/hoodie/hoodie_pim, 20),
		new /datum/data/retail_product("jacket",	/obj/item/clothing/suit/vampire/jacket,	15),
		new /datum/data/retail_product("grey flannel", /obj/item/clothing/suit/vampire/vtr/flannel, 20),
		new /datum/data/retail_product("red flannel", /obj/item/clothing/suit/vampire/vtr/flannel/red, 20),
		new /datum/data/retail_product("aqua flannel", /obj/item/clothing/suit/vampire/vtr/flannel/aqua, 20),
		new /datum/data/retail_product("brown flannel", /obj/item/clothing/suit/vampire/vtr/flannel/brown, 20),
		new /datum/data/retail_product("knee-high sneakers", /obj/item/clothing/shoes/vampire/vtr/pumped, 15),
		new /datum/data/retail_product("leopard coat", /obj/item/clothing/suit/vampire/vtr/coat/leopard, 20),
		new /datum/data/retail_product("moody attire", /obj/item/clothing/under/vampire/vtr/scenemoody, 20),
		new /datum/data/retail_product("odd Goth schoolgirl attire",	/obj/item/clothing/under/vampire/malkavian/female,	20),
		new /datum/data/retail_product("ripped punk jeans", /obj/item/clothing/under/vampire/vtr/rippedpunk, 20),
		new /datum/data/retail_product("gothic dress", /obj/item/clothing/under/vampire/vtr/dress/gothic, 25),
		new /datum/data/retail_product("pentagram dress", /obj/item/clothing/under/vampire/vtr/dress/pentagram, 25),
		new /datum/data/retail_product("pentagram shirt",	/obj/item/clothing/under/vampire/baali,	20),
		new /datum/data/retail_product("pentagram skirt",	/obj/item/clothing/under/vampire/baali/female,	20),
		new /datum/data/retail_product("pim attire", /obj/item/clothing/under/vampire/vtr/scenezim, 20),
		new /datum/data/retail_product("popular outfit", /obj/item/clothing/under/vampire/vtr/scenepink, 20),
		new /datum/data/retail_product("punk outfit",	/obj/item/clothing/under/vampire/emo,	20),
		new /datum/data/retail_product("red hipster outfit",	/obj/item/clothing/under/vampire/red,	20),
		new /datum/data/retail_product("revealing outfit", /obj/item/clothing/under/vampire/vtr/sceneleopard, 20),
		new /datum/data/retail_product("black choker", /obj/item/clothing/neck/vtr/choker, 20),
		new /datum/data/retail_product("silver choker", /obj/item/clothing/neck/vtr/choker/silver, 20),
		new /datum/data/retail_product("leather collar", /obj/item/clothing/neck/vtr/choker/collar, 50),
		new /datum/data/retail_product("fancy leather collar", /obj/item/clothing/neck/vtr/choker/collar/leatherg, 75),
		new /datum/data/retail_product("stainless steel collar", /obj/item/clothing/neck/vtr/choker/collar/steel, 100)
	)
