GLOBAL_LIST_INIT(hallucination_list_unweighted, list(
	/datum/hallucination/chat,
	/datum/hallucination/message,
	/datum/hallucination/sounds,
	/datum/hallucination/battle,
	/datum/hallucination/dangerflash,
	/datum/hallucination/weird_sounds,
	/datum/hallucination/stray_bullet,
	/datum/hallucination/husks,
	/datum/hallucination/fire,
	/datum/hallucination/self_delusion,
	/datum/hallucination/delusion,
	/datum/hallucination/shock,
	/datum/hallucination/death,
	/datum/hallucination/oh_yeah,
	/datum/hallucination/xeno_attack,
	/datum/hallucination/items_other,
	/datum/hallucination/hudscrew))
